"""
Django settings for subhub project.

Generated by 'django-admin startproject' using Django 5.0.6.

This file is based on your original settings and extended to include:
- Twilio config (fallback SMS)
- Optional SMTP/email config (for fallback or admin email use)
- Celery beat schedule entries for subscription check & pruning old notifications
- Notification tuning constants for broadcast batching
- All secrets read from environment (.env) — replace values in .env
"""

from pathlib import Path
from celery.schedules import crontab
import os
from dotenv import load_dotenv

# Load .env
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR defined above

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer reading SECRET_KEY from environment; fallback to an insecure default for dev only
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-replace-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') in ('True', 'true', '1')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'subhub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# MSG91 (existing)
MSG91_AUTH_KEY = os.getenv('MSG91_AUTH_KEY')
MSG91_SENDER_ID = os.getenv('MSG91_SENDER_ID', 'SUBHUB')
MSG91_ROUTE = os.getenv('MSG91_ROUTE', '4')
MSG91_COUNTRY = os.getenv('MSG91_COUNTRY', '91')

# Twilio (fallback)
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER')

# Optional Email (SMTP) settings (useful as fallback or for admin mails)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587) or 587)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') in ('True', 'true', '1')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@yourdomain.com')

# Database
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        # If you switch to Postgres / MySQL, provide DB_USER, DB_PASSWORD, DB_HOST, DB_PORT in .env
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery / Redis (existing)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = os.getenv('CELERY_TIMEZONE', 'UTC')

# Celery beat schedule (include your existing tasks + added prune task)
CELERY_BEAT_SCHEDULE = {
    # existing generate_alerts (if you have it implemented)
    'generate-alerts-daily': {
        'task': 'notifications.tasks.generate_alerts',
        'schedule': crontab(hour=0, minute=0),  # daily at midnight
    },
    # subscription internal notifications (already created earlier)
    'check-subscription-notifications': {
        'task': 'notifications.tasks.check_subscription_notifications',
        'schedule': crontab(hour=0, minute=10),  # runs daily at 00:10
    },
    # prune old notifications (auto-cleanup)
    'prune-old-notifications-daily': {
        'task': 'notifications.tasks.prune_old_notifications',
        'schedule': crontab(hour=3, minute=0),  # daily at 03:00
        'args': (int(os.getenv('NOTIFICATION_RETENTION_DAYS', 30)),),
    },
}

# Notification tuning (used by enqueue_broadcast task)
NOTIFICATION_BATCH_SIZE = int(os.getenv('NOTIFICATION_BATCH_SIZE', 50))
NOTIFICATION_BATCH_PAUSE_SECONDS = float(os.getenv('NOTIFICATION_BATCH_PAUSE_SECONDS', 1.0))
# How long to keep notifications before pruning (days)
NOTIFICATION_RETENTION_DAYS = int(os.getenv('NOTIFICATION_RETENTION_DAYS', 30))

# Auth user model
AUTH_USER_MODEL = 'notifications.User'

# Other optional settings (admins, logging) - keep simple for dev
ADMINS = tuple()  # e.g. (('Admin', 'admin@yourdomain.com'),)

# Simple logging setup for Celery / debug (optional - adjust as needed)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console':{'class': 'logging.StreamHandler',},
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
    },
}
