# Generated by Django 5.2.6 on 2025-09-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.CharField(max_length=20),
        ),
    ]
