# Generated by Django 5.0 on 2025-11-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
