# Generated by Django 5.0.14 on 2025-12-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_attempts_notification_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.EmailField(max_length=254),
        ),
    ]
