# Generated by Django 5.0.14 on 2025-12-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_last_attempt_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Netbanking', 'Netbanking'), ('Card', 'Card'), ('Wallet', 'Wallet')], max_length=20, null=True),
        ),
    ]
